-- MySQL Script generated by MySQL Workbench
-- Sun Jun  4 11:58:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajador` (
  `idTrabajador` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `ApPaterno` VARCHAR(30) NOT NULL,
  `ApMaterno` VARCHAR(30) NOT NULL,
  `Calle` VARCHAR(20) NOT NULL,
  `num` VARCHAR(8) NOT NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `cp` INT(8) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `tel` INT(10) NOT NULL,
  `sueldo` INT(8) NOT NULL,
  `ubicacion` VARCHAR(20) NOT NULL,
  `permisoPrestamo` BIT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idTrabajador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apPat` VARCHAR(30) NOT NULL,
  `apMat` VARCHAR(30) NOT NULL,
  `calle` VARCHAR(30) NOT NULL,
  `num` VARCHAR(8) NOT NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `cp` INT(8) NOT NULL,
  `tel` INT(10) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro` (
  `idLibro` VARCHAR(8) NOT NULL,
  `titulo` VARCHAR(20) NOT NULL,
  `editorial` VARCHAR(20) NOT NULL,
  `sinopsis` VARCHAR(300) NOT NULL,
  `idioma` VARCHAR(10) NOT NULL,
  `pais` VARCHAR(10) NOT NULL,
  `fechaPubli` DATE NOT NULL,
  `numPag` INT(8) NOT NULL,
  `Categoria_idCategoria` VARCHAR(8) NOT NULL,
  `ubicacion` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idLibro`, `Categoria_idCategoria`),
  INDEX `fk_Libro_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Libro_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Autor` (
  `idAutor` VARCHAR(8) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `apPaterno` VARCHAR(30) NOT NULL,
  `apMaterno` VARCHAR(30) NOT NULL,
  `lugarNacimiento` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prestamo` (
  `idPrestamo` VARCHAR(8) NOT NULL,
  `fechaPrestamo` DATETIME(6) NOT NULL,
  `fechaDevolucion` DATETIME(6) NOT NULL,
  `costoMulta` INT(20) NULL,
  `Usuario_idUsuario` VARCHAR(8) NOT NULL,
  `Trabajador_idTrabajador` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idPrestamo`, `Usuario_idUsuario`, `Trabajador_idTrabajador`),
  INDEX `fk_Prestamo_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Prestamo_Trabajador1_idx` (`Trabajador_idTrabajador` ASC),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idPrestamo` ASC),
  CONSTRAINT `fk_Prestamo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestamo_Trabajador1`
    FOREIGN KEY (`Trabajador_idTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro_has_Prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro_has_Prestamo` (
  `Libro_idLibro` VARCHAR(8) NOT NULL,
  `Prestamo_idPrestamo` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`Libro_idLibro`, `Prestamo_idPrestamo`),
  INDEX `fk_Libro_has_Prestamo_Prestamo1_idx` (`Prestamo_idPrestamo` ASC),
  INDEX `fk_Libro_has_Prestamo_Libro1_idx` (`Libro_idLibro` ASC),
  CONSTRAINT `fk_Libro_has_Prestamo_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Prestamo_Prestamo1`
    FOREIGN KEY (`Prestamo_idPrestamo`)
    REFERENCES `mydb`.`Prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Libro_has_Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Libro_has_Autor` (
  `Libro_idLibro` VARCHAR(8) NOT NULL,
  `Autor_idAutor` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`Libro_idLibro`, `Autor_idAutor`),
  INDEX `fk_Libro_has_Autor_Autor1_idx` (`Autor_idAutor` ASC),
  INDEX `fk_Libro_has_Autor_Libro1_idx` (`Libro_idLibro` ASC),
  CONSTRAINT `fk_Libro_has_Autor_Libro1`
    FOREIGN KEY (`Libro_idLibro`)
    REFERENCES `mydb`.`Libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Libro_has_Autor_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `mydb`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
